# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-CreationTime
version:      2.00
version_from: lib/File/CreationTime.pm
installdirs:  site
requires:
    File::ExtAttr:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
